### ISSUE TITLE
How to add captions to lightbox image?

### ISSUE THREAD

**Issue by hitherepeople100** [aldis-ameriks/photography-portfolio#588]
Hi there! I am a new photographer and was building a portfolio for my site when I came across this site. Thank you so much for making it available, I love it very much! I was wondering whether it is possible to add a short caption to the reac-images Lightbox. I understand that the functionality come with react-images, but I can't seem to find a way to implement it. I am a beginner (obviously lol) and any help is appreciated. Thanks!

**Comment by aldis-ameriks** [comment]
Hi, @hitherepeople100. I'm glad you've found it helpful.
react-images does support caption for images using the `caption` field on the photos array.

```
  state = {
    lightbox: false,
    photos: this.props.data.images.edges.map(image => ({
      srcSet: image.node.childImageSharp.fluid.srcSet,
      src: image.node.childImageSharp.fixed.src,
      thumbnail: image.node.childImageSharp.fixed.src,
      caption: 'This is the caption',
    })),
  }
```
